### ISSUE TITLE
Ubicación de los archivos package.json y package-lock.json

### ISSUE THREAD

**Issue by amartdom** [guillermoVicenteGonzalez/API-CRUD-Javasript#1]
Estos archivos deben estar en la raíz del proyecto y no en el directorio `config` como los tienes para poder solo abrir el repositorio puedas instalar las dependencias con el comando `npm install`

**Comment by guillermoVicenteGonzalez** [comment]
hecho

**Comment by amartdom** [comment]
En este caso no pasa nada pero para los próximos no cierres tú los issues porque así cuando los revise yo ya si están bien los cierro yo.
