### ISSUE TITLE
Uso de async/await en lugar de callbacks

### ISSUE THREAD

**Issue by amartdom** [guillermoVicenteGonzalez/API-CRUD-Javasript#2]
Mongoose y prácticamente todas las bibliotecas modernas de NPM permite esperar el resultado de las funciones con un mecanismo llamado async/await en lugar de utilizar el mecanismo de callback que siempre ensucia y complica el código. Por ejemplo la siguiente función que tienes escrita con callbacks:
```js
exports.findAllTVShows = function(req, res){
    TVShow.find(function(err,tvshows){
        if(err) res.send(500, err.message);

        console.log("GET /tvshows");
        res.status(200).jsonp(tvshows);
    });
};
```
Se simplificaría a la versión de async/await de la siguiente forma:
```js
exports.findAllTVShows = async function(req, res){
    let tvshows = await TVShow.find().catch(err => {return undefined});
    if(tvshows) {
        res.status(200).json(tvshows);
    }
    else{
        res.status(204).send();
    }
};
```
Así que cambia todas las funciones a este estilo

**Comment by guillermoVicenteGonzalez** [comment]
Las funciones add y find funcionan con cambios pero me he quedado bloqueado en updateTVShow. Al probar con postman no devuelve error sino que se queda en "sending request". Intuyo que debe ser un error o un despiste con el await pero no lo logro encontrar. He verificado que la id con la que hago la request existe. Subo el codigo a la rama features que creo que es lo que hay que hacer
![Captura de pantalla 2022-09-06 105437](https://user-images.githubusercontent.com/77115912/188592316-bdf19b25-847a-4557-b674-f68c9649f400.png)

**Comment by guillermoVicenteGonzalez** [comment]
ya encontré el error, me faltaba el .id.
Perdón por las molestias

**Comment by amartdom** [comment]
Te faltan unos parentesis a primera vista en `send` de la línea del 204 y para actualizar en vez de save se suele utilizar la función updateOne de la siguiente manera quedaría:
```js
let result = await TVShow.updateOne(req.params, tvshow).catch(err => {console.error(err);return undefined});
```

**Comment by guillermoVicenteGonzalez** [comment]
hecho. Creo que en la función deleteTVShow tengo elses redundantes pero no estoy seguro.
