### ISSUE TITLE
Crear archivo config.json en la raiz

### ISSUE THREAD

**Issue by amartdom** [guillermoVicenteGonzalez/API-CRUD-Javasript#4]
Crear un archivo en el que guardes todos los valores configurables como la conexión con la cadena de conexión de la base de datos y el puerto de bindeo de la API:
```json
{
    "mongoUrl": "mongodb://localhost:27017/tvshows",
    "port": 3000
}
```
Después para obtener los datos en el resto de archivos simplemente tienes que poner los siguiente:
```js
const config = require('../config.json') //.. si está en la carpeta anterior . si está en la misma

const mongoUrl = config.mongoUrl;
const port = config.port; 
```

**Comment by guillermoVicenteGonzalez** [comment]
hecho

**Comment by amartdom** [comment]
Perfecto
