### ISSUE TITLE
Crear directorio y archivo de rutas

### ISSUE THREAD

**Issue by amartdom** [guillermoVicenteGonzalez/API-CRUD-Javasript#5]
Para albergar las rutas que tienes puestas en el `app.js` lo suyo es crear un directorio `routes` y dentro un archivo `index.js` que tenga la siguiente forma:
```js
const { Router } = require('express');
const {getAllShows} = require('../controllers/tvshows');

const router = Router();

router.get('/tvshows',getAllShows);

module.exports = router;
```
Y después ya en `app.js` importarlo y ponerlo a uso de la siguiente manera:

```js
const router = require('./routes/index')

app.use('/api',router);
```

**Comment by guillermoVicenteGonzalez** [comment]
hecho, aunque no se si exactamente como  me pedías.

**Comment by amartdom** [comment]
No es como dije pero también es correcto
